require("./tasks/generate-contract");
require("./tasks/generate-deployment");
require("./tasks/deploy-everything");
require("./tasks/transfer");
require("./tasks/ownership");
require("./tasks/erc20");
require("./tasks/erc721");
require("./tasks/erc1155");
require("./tasks/ipfs");
